### ISSUE TITLE
Export and import alarms and settings

### ISSUE THREAD

**Issue by Raffael7777** [gabeg805/NFC-Alarm-Clock#13]
The 12.3 release was signed with a different certificate than the one used to sign the 12.2 release (using the foss release apk both times). This meant F-Droid/Droidify would not update until the previous version was uninstalled. Uninstalling removed all previous alarms, saved NFC tags, and custom settings.

It would be nice to be able to export all settings, including saved NFC tags, and alarms created to a file, and be able to import such files to restore those settings, saved tags, and created alarms. Not only would this alievate issues like the one described above, but it would also make migrating to a new device much easier for users.

**Comment by gabeg805** [comment]
Hi @Raffael7777, this is really strange.  I would sometimes create releases on my laptop and sometimes on my desktop.  I just ran a diff on the key they both use and they're exactly the same.  I'm really not sure why they would be signed differently...I think if you used F-Droid, they might do the signing themselves, since the code is on Github, they'd be able to sign it?  That's the only thing I can think of though.

I'll work on implementing the import/export though.  Thanks for suggestion and sorry this happened to you!

**Comment by gabeg805** [comment]
Hey @Raffael7777, I fixed the big in v12.4.0 so everything should be all set with this feature.  I'm going to close it, but let me know if you have any problems.
