### ISSUE TITLE
text to speech (tts) should be configured according to locale

### ISSUE THREAD

**Issue by 573** [gabeg805/NFC-Alarm-Clock#14]
Nice package !

While using I found that the tts reads a mix of english and the locale the time is configured in on the device, i. e. for german locale: "the time is zehn uhr neun".

**Comment by gabeg805** [comment]
Thanks @573!  It's hard to add translations for every language because I have to resort to Google Translate and it gets really time consuming, but I'm doing what I can!  

I added German and it'll now say the sentence fully in German, no mix of English and German.  If you catch any other weird TTS issues, just let me know in the other issue you have opened.  I wasn't able to close the other one because it takes an understanding of the language that I don't have, but I'll close this one since I was able to test it and TTS did say everything in German.
