### ISSUE TITLE
Allow dismiss without unlocking the device

### ISSUE THREAD

**Issue by lu-x** [gabeg805/NFC-Alarm-Clock#3]
Currently the device has to be unlocked to stop an alarm. It'd be helpful if the screen automatically turns on and you can directly stop the alarm instead.
Besides that this is a great app 🙂

**Comment by gabeg805** [comment]
Hi @lu-x, you can already do that, but if you have NFC set for dismissing alarms, this is unfortunately impossible.  It's an Android security issue where the system doesn't allow me to enable the app to scan for NFC tags if the phone is locked.  That's why I made it so that the app doesn't show if your phone is locked and you have NFC set for dismissing alarms.

**Comment by lu-x** [comment]
I forgot to mention NFC in my description, your response makes sense, thank you.
