### ISSUE TITLE
Option to hide dismiss button

### ISSUE THREAD

**Issue by Donkey-Doug** [gabeg805/NFC-Alarm-Clock#6]
Please make it possible to hide the dismiss button, because it is now very easy to accidentally press dismiss when my intention was to press snooze.

An alternative would be to have to press and hold the dismiss button

**Comment by gabeg805** [comment]
Hi @Donkey-Doug, if you set the alarm to require NFC in order to dismiss, it won't show the dismiss button.  I've been thinking about changing up how the snooze and dismiss button are interacted with, like a press and hold type thing like you're saying, but I just haven't gotten around to it yet.  In the meantime, I'd suggest the NFC tag route.

**Comment by gabeg805** [comment]
Hi @Donkey-Doug, just wanted to let you know that I'm working on this feature next, so in one of the next updates, you'll see this.  I'm planning on it being opt-in, so that people that use the old Snooze/Dismiss layout will still be able to use it.  It'll probably be something like in: Settings > Appearance, I'll have a thing to change how the dismissing and snoozing an alarm looks.

**Comment by gabeg805** [comment]
Hi @Donkey-Doug, I just updated the app to version 12.1.2.  It's got a new alarm screen that you can enable in Settings > Appearance.  You can download the apk/aab from the releases tab, or you can wait for the version to hit the Google Play store.  I submitted the new version to Google already, but it always takes like 30 min to some # of hours before it becomes live on the Play store.

Hope you like it!
